### ISSUE TITLE
[Feat] 카메라 움직임 + 최적화 관련

### ISSUE THREAD

**Issue by JangHanjun** [NoHornDragon/NoHornDragon_GameDev#6]
## 개요

이전 프로젝트와 달리 방 to 방의 레벨 디자인에서 벗어나 카메라 1대를 통해 연출을 하게 되었으며 추가적으로 배경에 전경, 후경 효과가 생기게 되어서 이와 관련해서 최적화를 해야 할 것 같습니다.

## 현재 상황
77d1dd24b9aa9eba1fbc5d2139fded3dcd293bea
현재 카메라 1대를 통해 각 방을 감싸는 confiner를 지날 때마다 방 번호, 스테이지 번호를 체크해 해당하는 곳의 방과 배경을 켜주는 시스템입니다.
다만 방들은 플레이어 기준으로 +- 1칸의 방들을 SetActive(true)를 해주는 반면 배경의 경우 스테이지별 관리를 통해서 SetActive 호출 빈도가 적은 편입니다. 또한 confiner들이 각 방으로 나뉘어진 이유도 이전의 카메라 2개를 통한 연출이 큰 이유였으니 이번 기회에 이를 바꿔보려고 합니다.

## TODO
- [x] confiner를 스테이지 1개로 감싸기
- [x] 스테이지를 지날때 confiner 변경하기
- [x] RoomManager에서 각 방을 수시로 SetActive 하는것에서 스테이지 단위로 SetActive 하는걸로 변경

**Comment by JangHanjun** [comment]
## 해결
위 방안대로 방별 이동에서 벗어나 스테이지별 이동을 했으며 start 함수에서 배경을 로드한 뒤 무조건 false 하는 방식으로 했습니다.
이후 유니티의 라이프 사이클에 따라서 ontriggerenter가 불리게 되고 1스테이지가 로드되는 그런 방식입니다.

## 관련 커밋
780ee636510a58545c9efbd5396b74485fc21475
7a27ab405c4d7d016caf7c4a7e4e5cd21156e671
169a24bb240060bd75fb671b4e47730b2b43bac6
